# Generated by Django 3.0.5 on 2020-11-13 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.TextField()),
                ('lat', models.FloatField(default=0, max_length=300)),
                ('lng', models.FloatField(default=0, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50)),
                ('user_name', models.CharField(default='', max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.User')),
                ('posts', models.ManyToManyField(to='map.Diary')),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.User'),
        ),
    ]
