# Generated by Django 3.0.5 on 2020-11-13 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapYourDiary',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_bool', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlacePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.TextField()),
                ('lat', models.FloatField(default=0, max_length=300)),
                ('lng', models.FloatField(default=0, max_length=300)),
                ('likes', models.ManyToManyField(default=0, related_name='liker', to='map.PostLike')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.MapYourDiary')),
            ],
        ),
    ]
