<<<<<<< HEAD
# Generated by Django 3.0.5 on 2020-11-09 17:01
=======
# Generated by Django 3.1.2 on 2020-11-10 05:10
>>>>>>> 9608ad4d9c0aa6c9fb07eaaf48d7237fd7e46247

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
